# Generated by Django 2.2.3 on 2019-08-22 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photogur', '0003_picture_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='user_id',
            new_name='user',
        ),
    ]
